### ISSUE TITLE
Licenses on Container Generated Files

### ISSUE THREAD

**Issue by nonelement** [480Oswego2013/CSC-HCI-480-2013-repo#18]
When building the project, licenses are not present on (presumably)generated files, and cause builds to fail unless inserted manually. 

(/Web Pages/WEB-INF/glassfish-web.xml, for example, for my environment.)

**Comment by kevinwinahradsky** [comment]
If this is a generated file it should be generated into the target directory. Do you know what generates it?

As far as I know, most people are using tomcat rather than glassfish so you shouldn't have any problems with that. Also if it contains nothing specific to your environment, like directory paths, then you can probably just commit it for other people who want to use glassfish.

**Comment by nonelement** [comment]
I assume the file is generated by building and running with Glassfish, since it doesn't appear before then. I'd heard that at least one person was using Glassfish, so I decided to use that. Nothing more than a whim, really, and I'm not sure differences between containers are detrimental at this point.

There isn't anything specific to my environment in the file beyond a specific Glassfish version number in the doctype definition. If this can be ignored, I'll commit it.

**Comment by kevinwinahradsky** [comment]
Yeah you might as well commit it.
