### ISSUE TITLE
Team Test Stuff

### ISSUE THREAD

**Issue by 480Oswego2013** [480Oswego2013/CSC-HCI-480-2013-repo#21]
New Tasks
hey team this time we are working on the Presenter stuff 
sorry the update took so long here is what we are to test

keep up the good work guys!

Presenter classes

ConfusionMatrixPresenter.java -

ConfusionMatrixPresenterImpl.java -

DataPanelPresenter.java -

DataPanelPresenterImpl.java -

DoublePanelPresenter.java -

RfParametersPresenter.java -

RfParametersPresenterImpl.java -

TabPanelPresenter.java - j

TreePanelPresenter.java -

Here are some classes that you can test if you are not up for doing interfaces tests

Test for the activity package

TreeVisActivity.java -

DoublePanelActivity.java -

DataPanelActivity.java -

ConfusionMatrixActivity.java -

AppActivityMapper.java -

TreePanelPresenterImpl.java -

**Comment by kevinwinahradsky** [comment]
Since the json stuff are just data objects with no logic, they don't really need tests. Also note that for the most part they have no setters or usable constructors. The are generally created only through deserialization of json. So if you do test them they will need a bunch of code added to them.

Ideally we really need to get the presenters and activities tested, anything that has any sort of logic behind it.
