### ISSUE TITLE
Add suggestion for forest size

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#28]
Subjects did not understand the correlation between this parameter and the resulting forest size. This resulted in subjects trying arbitrary forest sizes, and consequently becoming overwhelmed by the confusion matrix size, as well as lost in the corresponding visualizations. Aside: adjust the error message to provide help with the task of selecting appropriate parameters, not necessarily helping the user enter a valid value.
Severity Rating: 2

**Comment by cbchd** [comment]
Nate is assigned

**Comment by nonelement** [comment]
Parameters in general proved to be a problem for two subjects this last round. Each user spent ~2 minutes trying various values for the parameters in order to generate a forest. How to avoid this problem is a tough question though, because we'd have to exclude parameters based on what the user is selecting, which would be based on preprocessing the data.
