### ISSUE TITLE
Horizontal scrolling, once matrix becomes too large

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#35]
Two users had difficulty navigating the confusion matrix horizontally if the generated matrix was too large. One user navigated the matrix with the arrow keys and selecting text because he perceived no other options

Severity Rating: 4

**Comment by kevinwinahradsky** [comment]
This was mostly fixed in #17.  I do believe there may still be an issue with the bottom scroll bar not showing under some situations. I have not been able to consistently replicate it though and it almost always works fine for me. This is why the arrow keys will work for scrolling. 

So we need some more info on when this is not seen by people.

**Comment by nonelement** [comment]
This can be formed into a task for which we can test.
