### ISSUE TITLE
Display of parameters to show what settings were used in the forest generation

### ISSUE THREAD

**Issue by agylardi** [480Oswego2013/CSC-HCI-480-2013-repo#36]
Users were generally selecting parameters at random, and had difficulty remembering what parameters a previous forest was generated with for comparison. One subject generated two forests in order to compare differences between two confusion matrices

Severity Rating: 2

**Comment by patricktoohey** [comment]
Confusion matrix view shows the index of the classification variable instead of the text value. Further, the text is inconsistent between the confusion matrix view and the request view. The request uses "Classification Variable" while the confusion matrix view uses "Response Variable". This is likely adding to confusion on this issue.

**Comment by nonelement** [comment]
Added consistency may help improve clarity, as you're suggesting, @bahbah2e . Specifically, perhaps we can test for comprehension on each item included in the CF view. (For example, what's mtry?)

**Comment by cbchd** [comment]
Place parameters next to the confusion matrix
