### ISSUE TITLE
Design Document

### ISSUE THREAD

**Issue by patricktoohey** [480Oswego2013/CSC-HCI-480-2013-repo#49]
First draft

**Comment by nhoefer2** [comment]
https://github.com/480Oswego2013/CSC-HCI-480-2013-repo/wiki/Design-docs
These were made using Acceleo plugin for eclipse.

**Comment by patricktoohey** [comment]
I am happy with the current implementation. Please comment on any additional needs.

**Comment by kevinwinahradsky** [comment]
Looks good enough to me at this point I think. Not sure if anyone else has any new sections or some tweaks they want to add though.

**Comment by adarwin** [comment]
I think the document would flow a little better if the class and package diagrams were embedded before the "Future Enhancement Opportunities" section, instead of linked at the end of the document. If it turns out that embedding the diagrams makes them illegibly small, then leaving them as links is fine.

Other than that, I think the document is good as is.

**Comment by kevinwinahradsky** [comment]
Move the images up and inlined them, and kept the links as well. I think their legibility is going to depend on someones monitor size.

**Comment by adarwin** [comment]
Excellent. Looks good to me now. :-)

**Comment by patricktoohey** [comment]
I vote 'Closed'

**Comment by kevinwinahradsky** [comment]
If no more comments by 5 then I think we are in good shape to close this as well

**Comment by eneil** [comment]
Yeah this looks excellent, very well done.

On Mon, May 13, 2013 at 11:54 AM, kevinwinahradsky <notifications@github.com

**Comment by adarwin** [comment]
I vote we give it 'til 3:00, in case anyone else has input. Then we'll close it.

**Comment by kevinwinahradsky** [comment]
closing!
